name: npm package

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm i -g @angular/cli@17.0.0
      - run: ng build knd-dragAndDrop
      - name: NPM Publish
        run: |
          git config user.email "ci@codeandcomments.at"
          git config user.name "ci"
          cd dist/knd-drag-and-drop
          npm version "${{  github.ref_name }}"
          npm publish --access public
        env:
          NODE_AUTH_TOKEN:  ${{ secrets.NPM_TOKEN }}
